### ISSUE TITLE
How to change x/y or w/h values per breakpoint

### ISSUE THREAD

**Issue by fluxxus** [okydk/basegrid#4]
Since `--x` , `--y`, `--w` and `--h` are declared inline, is it possible to change those at certain breakpoint?

I find it common to change column size per certain breakpoint. Also positioning items differently with `--x`  and  `--y` would be very handy.

p.s. Maybe what I am asking is too much, but do you maybe have an example of a simple responsive layout built with `basegrid`? A Codepen or similar?

**Comment by okydk** [comment]
Sure! Since it's just CSS-variables you can set them as such:
```css
.myDiv{
    --w: 6;
}
@media (max-width: 800px) {
    .myDiv{
        --w: 12;
    }
}
```
Note that if you don't set `--x` & `--y` it will auto flow. ;)
Good idea with the Codepen - might set something up when I have time.
